spring.application.name=Animal-Shelter-Bot

spring.datasource.url=your_db_url
spring.datasource.username=your_db_username
spring.datasource.password=tour_db_password
telegram.bot.token=your_bot_token

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

telegram.bot.volunteer-chat-id=123456789